package cho.carbon.fg.eln.rule.materialratiocelne3466.f2imp

import cho.carbon.relation.RelationCorrelation;
import cho.carbon.fuse.improve.attribute.FuseAttributeFactory;
import cho.carbon.rrc.record.FGAttribute;
import cho.carbon.meta.enun.AttributeValueType;
import cho.carbon.relation.RecordRelation;
import cho.carbon.fuse.improve.attribute.FuseAttribute;
import cho.carbon.fuse.improve.attribute.OpsAttribute;
import cho.carbon.fuse.improve.attribute.mline.OpsMLineAttr;
import cho.carbon.message.MessageFactory;
import cho.carbon.fg.eln.common.CommonCalculation;
import cho.carbon.fg.eln.constant.BaseConstant;
import cho.carbon.fg.eln.constant.EnumKeyValue;
import cho.carbon.fg.eln.constant.RelationType;
import cho.carbon.fg.eln.constant.item.MaterialRatioCELNE3466Item;


global java.lang.String recordCode;
global java.lang.String userCode;
global java.lang.String recordName;
global java.lang.String hostCode; 
global java.lang.String hostName;
global cho.carbon.rrc.record.FGRootRecord record;
global cho.carbon.complexus.FGRecordComplexus recordComplexus;
global cho.carbon.fuse.improve.ops.builder.FGRecordOpsBuilder recordOpsBuilder;
global java.util.List<FGRootRecord> relatedRecordList;
global java.util.List<Updatable> updateBeans;
global java.util.List<RemoveRecordInfo> removeRecordInfoList;
global java.util.List<RecordRelationOpsBuilder>  relatedRelationOpsBuilderList;
global cho.carbon.ops.builder.RecordRelationOpsBuilder relationOpsBuilder;
global java.util.List<Message> messageList;

rule "投料量单位必填"
	when
		not FuseAttribute(name == MaterialRatioCELNE3466Item.基本属性组_投料量单位) 
		or FuseAttribute(name == MaterialRatioCELNE3466Item.基本属性组_投料量单位, CommonCalculation.isNotBasicLawful(getValue(AttributeValueType.STRING)));
	then
		messageList.add(MessageFactory.buildRefuseMessage("Failed", "投料信息", BaseConstant.TYPE_实验记录, "投料单位必填"));
end



/*
rule "默认计划投料量"
	salience 20
	when
		not FuseAttribute(name==MaterialRatioCELNE3466Item.基本属性组_计划投料量) 
		or FuseAttribute(name==MaterialRatioCELNE3466Item.基本属性组_计划投料量,CommonCalculation.isNotBasicLawful(getValue(AttributeValueType.STRING)));
		 FuseAttribute(name==MaterialRatioCELNE3466Item.基本属性组_实际投料量,  value:getValue(AttributeValueType.STRING)) 
	then 
		// 计划投料量为空， 那么把实际投料量赋值给计划
		FGAttribute attr=FuseAttributeFactory.buildAttribute(MaterialRatioCELNE3466Item.基本属性组_计划投料量, value);
		recordOpsBuilder.addUpdateAttr(attr);	
end
*/


