package cho.carbon.fg.eln.rule.materialoutinrecordcelne3558.idquery

import cho.carbon.fuse.improve.attribute.FuseAttribute;
import cho.carbon.query.model.FGConJunctionFactory;
import cho.carbon.meta.enun.AttributeValueType;
import cho.carbon.meta.enun.operator.UnaryOperator;
import cho.carbon.fg.eln.common.CommonCalculation;
import cho.carbon.fg.eln.constant.BaseConstant;
import cho.carbon.fg.eln.constant.item.MaterialOutInRecordCELNE3558Item;

global java.lang.String recordName;
global cho.carbon.query.model.FGConJunctionFactory conJunctionFactory;

