package cho.carbon.fg.eln.rule.materialreservationcelne3756.impsecond

import cho.carbon.relation.RelationCorrelation;
import cho.carbon.fuse.improve.attribute.FuseAttributeFactory;
import cho.carbon.rrc.record.FGAttribute;
import cho.carbon.meta.enun.AttributeValueType;
import cho.carbon.relation.RecordRelation;
import cho.carbon.fuse.improve.attribute.FuseAttribute;
import cho.carbon.fuse.improve.attribute.OpsAttribute;
import cho.carbon.fuse.improve.attribute.mline.OpsMLineAttr;
import cho.carbon.message.MessageFactory;
import cho.carbon.fg.eln.common.CommonCalculation;
import cho.carbon.fg.eln.constant.BaseConstant;
import cho.carbon.fg.eln.constant.EnumKeyValue;
import cho.carbon.fg.eln.constant.RelationType;
import cho.carbon.fg.eln.constant.item.MaterialReservationCELNE3756Item;


global java.lang.String recordCode;
global java.lang.String userCode;
global java.lang.String recordName;
global java.lang.String hostCode; 
global java.lang.String hostName;
global cho.carbon.rrc.record.FGRootRecord record;
global cho.carbon.complexus.FGRecordComplexus recordComplexus;
global cho.carbon.fuse.improve.ops.builder.FGRecordOpsBuilder recordOpsBuilder;
global java.util.List<FGRootRecord> relatedRecordList;
global java.util.List<Updatable> updateBeans;
global java.util.List<RemoveRecordInfo> removeRecordInfoList;
global java.util.List<RecordRelationOpsBuilder>  relatedRelationOpsBuilderList;
global cho.carbon.ops.builder.RecordRelationOpsBuilder relationOpsBuilder;
global java.util.List<Message> messageList;


rule "物料预订人"
	salience 30 
	when
		not RecordRelation(type == RelationType.RR_物料预定_预定人_系统用户);
	then  
		relationOpsBuilder.putRelation(RelationType.RR_实验项目_创建人_系统用户, userCode);
end

rule "实验项目必填"
	salience 30 
	when
		not RecordRelation(type == RelationType.RR_物料预定_所属项目_实验项目);
	then  
		messageList.add(MessageFactory.buildRefuseMessage("Failed", "实验项目", BaseConstant.TYPE_物料预定, "实验项目必填"));
end

rule "预定物料必填"
	salience 30 
	when
		not RecordRelation(type == RelationType.RR_物料预定_预定物料_投料信息);
	then  
		messageList.add(MessageFactory.buildRefuseMessage("Failed", "预定物料", BaseConstant.TYPE_物料预定, "预定物料必填"));
end
