package cho.carbon.fg.eln.rule.materialstockinfocelne3551.f2imp

import cho.carbon.relation.RelationCorrelation;
import cho.carbon.fuse.improve.attribute.FuseAttributeFactory;
import cho.carbon.rrc.record.FGAttribute;
import cho.carbon.meta.enun.AttributeValueType;
import cho.carbon.relation.RecordRelation;
import cho.carbon.fuse.improve.attribute.FuseAttribute;
import cho.carbon.fuse.improve.attribute.OpsAttribute;
import cho.carbon.fuse.improve.attribute.mline.OpsMLineAttr;
import cho.carbon.message.MessageFactory;
import cho.carbon.fg.eln.common.CommonCalculation;
import cho.carbon.fg.eln.constant.BaseConstant;
import cho.carbon.fg.eln.constant.EnumKeyValue;
import cho.carbon.fg.eln.constant.RelationType;
import cho.carbon.fg.eln.constant.item.MaterialStockInfoCELNE3551Item;
import cho.carbon.fg.eln.algorithm.eln.MaterialStockAlgorithm;

global java.lang.String recordCode;
global java.lang.String userCode;
global java.lang.String recordName;
global java.lang.String hostCode; 
global java.lang.String hostName;
global cho.carbon.rrc.record.FGRootRecord record;
global cho.carbon.complexus.FGRecordComplexus recordComplexus;
global cho.carbon.fuse.improve.ops.builder.FGRecordOpsBuilder recordOpsBuilder;
global java.util.List<FGRootRecord> relatedRecordList;
global java.util.List<Updatable> updateBeans;
global java.util.List<RemoveRecordInfo> removeRecordInfoList;
global java.util.List<RecordRelationOpsBuilder>  relatedRelationOpsBuilderList;
global cho.carbon.ops.builder.RecordRelationOpsBuilder relationOpsBuilder;
global java.util.List<Message> messageList;


rule "计算高低库存"
	when
		FuseAttribute( name == MaterialStockInfoCELNE3551Item.基本属性组_是否更新阈值, getValue(AttributeValueType.INT) == EnumKeyValue.ENUM_是否_是)
	then 
		FGAttribute attr=FuseAttributeFactory.buildAttribute(MaterialStockInfoCELNE3551Item.基本属性组_是否更新阈值, null);
		recordOpsBuilder.addUpdateAttr(attr);	
		messageList.add(MaterialStockAlgorithm.calculateMaterialStockInfo(recordComplexus, recordCode, recordOpsBuilder));
end
