package cho.carbon.fg.eln.rule.materiainfocelne3393.f1pre

import cho.carbon.relation.RelationCorrelation;
import cho.carbon.fuse.improve.attribute.FuseAttributeFactory;
import cho.carbon.rrc.record.FGAttribute;
import cho.carbon.meta.enun.AttributeValueType;
import cho.carbon.relation.RecordRelation;
import cho.carbon.fuse.improve.attribute.FuseAttribute;
import cho.carbon.fuse.improve.attribute.OpsAttribute;
import cho.carbon.fuse.improve.attribute.mline.OpsMLineAttr;
import cho.carbon.message.MessageFactory;
import cho.carbon.fg.eln.common.CommonCalculation;
import cho.carbon.fg.eln.constant.BaseConstant;
import cho.carbon.fg.eln.constant.EnumKeyValue;
import cho.carbon.fg.eln.constant.RelationType;
import cho.carbon.fg.eln.constant.item.MateriaInfoCELNE3393Item;
import cho.carbon.fg.eln.algorithm.eln.MateriaInfoAlgorithm;


global java.lang.String recordCode;
global java.lang.String userCode;
global java.lang.String recordName;
global java.lang.String hostCode; 
global java.lang.String hostName;
global cho.carbon.rrc.record.FGRootRecord record;
global cho.carbon.complexus.FGRecordComplexus recordComplexus;
global cho.carbon.fuse.improve.ops.builder.FGRecordOpsBuilder recordOpsBuilder;
global java.util.List<FGRootRecord> relatedRecordList;
global java.util.List<Updatable> updateBeans;
global java.util.List<RemoveRecordInfo> removeRecordInfoList;
global java.util.List<RecordRelationOpsBuilder>  relatedRelationOpsBuilderList;
global cho.carbon.ops.builder.RecordRelationOpsBuilder relationOpsBuilder;
global java.util.List<Message> messageList;

rule "不能更改基础计量单位"
	when
		OpsAttribute( name == MateriaInfoCELNE3393Item.基本属性组_基础计量单位,$opsValue : getValue(AttributeValueType.STRING) );
		FuseAttribute( name == MateriaInfoCELNE3393Item.基本属性组_基础计量单位, $fuseValue : getValue(AttributeValueType.STRING) );
		eval(!$opsValue.equals($fuseValue))
	then
		messageList.add(MateriaInfoAlgorithm.updateBaseUnit( recordComplexus,  recordCode,   relatedRelationOpsBuilderList,  $opsValue,  $fuseValue));
		 //  messageList.add(MessageFactory.buildRefuseMessage("Failed", "警告", BaseConstant.TYPE_物料基础信息, "物料基础计量单位不允许更改"));
end
