package cho.carbon.fg.eln.rule.weekmonthreportcelne4037.impsecond

import cho.carbon.relation.RelationCorrelation;
import cho.carbon.fuse.improve.attribute.FuseAttributeFactory;
import cho.carbon.rrc.record.FGAttribute;
import cho.carbon.meta.enun.AttributeValueType;
import cho.carbon.relation.RecordRelation;
import cho.carbon.fuse.improve.attribute.FuseAttribute;
import cho.carbon.fuse.improve.attribute.OpsAttribute;
import cho.carbon.fuse.improve.attribute.mline.OpsMLineAttr;
import cho.carbon.message.MessageFactory;
import cho.carbon.fg.eln.common.CommonCalculation;
import cho.carbon.fg.eln.constant.BaseConstant;
import cho.carbon.fg.eln.constant.EnumKeyValue;
import cho.carbon.fg.eln.constant.RelationType;
import cho.carbon.fg.eln.constant.item.WeekMonthReportCELNE4037Item;
import cho.carbon.fg.eln.algorithm.eln.WeekMonthReportAlgorithm;


global java.lang.String recordCode;
global java.lang.String userCode;
global java.lang.String recordName;
global java.lang.String hostCode; 
global java.lang.String hostName;
global cho.carbon.rrc.record.FGRootRecord record;
global cho.carbon.complexus.FGRecordComplexus recordComplexus;
global cho.carbon.fuse.improve.ops.builder.FGRecordOpsBuilder recordOpsBuilder;
global java.util.List<FGRootRecord> relatedRecordList;
global java.util.List<Updatable> updateBeans;
global java.util.List<RemoveRecordInfo> removeRecordInfoList;
global java.util.List<RecordRelationOpsBuilder>  relatedRelationOpsBuilderList;
global cho.carbon.ops.builder.RecordRelationOpsBuilder relationOpsBuilder;
global java.util.List<Message> messageList;

rule "周月总结的创建人"
	salience 30 
	when
		not RecordRelation(type == RelationType.RR_周月总结_创建人_系统用户);
	then  
		relationOpsBuilder.putRelation(RelationType.RR_周月总结_创建人_系统用户, userCode);
end

rule "生成周月总结报告"
	salience 20
	when
		FuseAttribute(name==WeekMonthReportCELNE4037Item.基本属性组_周月总结命令,getValue(AttributeValueType.INT) == EnumKeyValue.ENUM_周月总结命令_生成报告);
	then  
		// 置空生成命令
		FGAttribute attr=FuseAttributeFactory.buildAttribute(WeekMonthReportCELNE4037Item.基本属性组_周月总结命令, null);
		recordOpsBuilder.addUpdateAttr(attr);	
		// 记性报告的生成
		messageList.add(WeekMonthReportAlgorithm.createWeekMonthReport(recordComplexus, recordCode, recordOpsBuilder, relatedRecordList, userCode));
end

