package cho.carbon.fg.eln.rule.instrumentoutinrecordcelne3894.f2imp

import cho.carbon.relation.RelationCorrelation;
import cho.carbon.fuse.improve.attribute.FuseAttributeFactory;
import cho.carbon.rrc.record.FGAttribute;
import cho.carbon.meta.enun.AttributeValueType;
import cho.carbon.relation.RecordRelation;
import cho.carbon.fuse.improve.attribute.FuseAttribute;
import cho.carbon.fuse.improve.attribute.OpsAttribute;
import cho.carbon.fuse.improve.attribute.mline.OpsMLineAttr;
import cho.carbon.message.MessageFactory;
import cho.carbon.fg.eln.common.CommonCalculation;
import cho.carbon.fg.eln.constant.BaseConstant;
import cho.carbon.fg.eln.constant.EnumKeyValue;
import cho.carbon.fg.eln.constant.RelationType;
import cho.carbon.fg.eln.constant.item.InstrumentOutInRecordCELNE3894Item;


global java.lang.String recordCode;
global java.lang.String userCode;
global java.lang.String recordName;
global java.lang.String hostCode; 
global java.lang.String hostName;
global cho.carbon.rrc.record.FGRootRecord record;
global cho.carbon.complexus.FGRecordComplexus recordComplexus;
global cho.carbon.fuse.improve.ops.builder.FGRecordOpsBuilder recordOpsBuilder;
global java.util.List<FGRootRecord> relatedRecordList;
global java.util.List<Updatable> updateBeans;
global java.util.List<RemoveRecordInfo> removeRecordInfoList;
global java.util.List<RecordRelationOpsBuilder>  relatedRelationOpsBuilderList;
global cho.carbon.ops.builder.RecordRelationOpsBuilder relationOpsBuilder;
global java.util.List<Message> messageList;

rule "设置默认出入库状态"
	salience 20
	when
		not FuseAttribute( name == InstrumentOutInRecordCELNE3894Item.基本属性组_仪器出入库状态);
		or FuseAttribute( name == InstrumentOutInRecordCELNE3894Item.基本属性组_仪器出入库状态, CommonCalculation.isNotBasicLawful(getValue(AttributeValueType.STRING)));
	then
		FGAttribute attr=FuseAttributeFactory.buildAttribute(InstrumentOutInRecordCELNE3894Item.基本属性组_仪器出入库状态, EnumKeyValue.ENUM_仪器出入库状态_编辑中);
		recordOpsBuilder.addUpdateAttr(attr);	
end
