package cho.carbon.fg.eln.rule.elnprojectcelne2244.f2imp

import cho.carbon.relation.RelationCorrelation;
import cho.carbon.fuse.improve.attribute.FuseAttributeFactory;
import cho.carbon.rrc.record.FGAttribute;
import cho.carbon.meta.enun.AttributeValueType;
import cho.carbon.relation.RecordRelation;
import cho.carbon.fuse.improve.attribute.FuseAttribute;
import cho.carbon.fuse.improve.attribute.OpsAttribute;
import cho.carbon.fuse.improve.attribute.mline.OpsMLineAttr;
import cho.carbon.message.MessageFactory;
import cho.carbon.fg.eln.common.CommonCalculation;
import cho.carbon.fg.eln.constant.BaseConstant;
import cho.carbon.fg.eln.constant.EnumKeyValue;
import cho.carbon.fg.eln.constant.RelationType;
import cho.carbon.fg.eln.constant.item.ElnprojectCELNE2244Item;
import java.util.Date;

global java.lang.String recordCode;
global java.lang.String userCode;
global java.lang.String recordName;
global java.lang.String hostCode; 
global java.lang.String hostName;
global cho.carbon.rrc.record.FGRootRecord record;
global cho.carbon.complexus.FGRecordComplexus recordComplexus;
global cho.carbon.fuse.improve.ops.builder.FGRecordOpsBuilder recordOpsBuilder;
global java.util.List<FGRootRecord> relatedRecordList;
global java.util.List<Updatable> updateBeans;
global java.util.List<RemoveRecordInfo> removeRecordInfoList;
global java.util.List<RecordRelationOpsBuilder>  relatedRelationOpsBuilderList;
global cho.carbon.ops.builder.RecordRelationOpsBuilder relationOpsBuilder;
global java.util.List<Message> messageList;


rule "设置实验项目状态"
	salience 20
	when
		not FuseAttribute(name==ElnprojectCELNE2244Item.基本属性组_项目状态) 
		or FuseAttribute(name==ElnprojectCELNE2244Item.基本属性组_项目状态,CommonCalculation.isNotBasicLawful(getValue(AttributeValueType.STRING)));
	then
		// 生成实验项目状态
		FGAttribute attr=FuseAttributeFactory.buildAttribute(ElnprojectCELNE2244Item.基本属性组_项目状态, EnumKeyValue.ENUM_项目状态_筹划中);
		recordOpsBuilder.addUpdateAttr(attr);	
end

rule "设置存档状态"
	salience 20
	when
		not FuseAttribute(name==ElnprojectCELNE2244Item.基本属性组_存档状态) 
		or FuseAttribute(name==ElnprojectCELNE2244Item.基本属性组_存档状态,CommonCalculation.isNotBasicLawful(getValue(AttributeValueType.STRING)));
	then 
		// 设置存档状态
		FGAttribute attr=FuseAttributeFactory.buildAttribute(ElnprojectCELNE2244Item.基本属性组_存档状态, EnumKeyValue.ENUM_实验存档状态_未存档);
		recordOpsBuilder.addUpdateAttr(attr);	
end

rule "设置实验项目启动日期"
	salience 20
	when
		not FuseAttribute(name == ElnprojectCELNE2244Item.基本属性组_启动日期) 
		or FuseAttribute(name == ElnprojectCELNE2244Item.基本属性组_启动日期,CommonCalculation.isNotBasicLawful(getValue(AttributeValueType.STRING)));
	then 
		// 生成实验项目启动日期
		FGAttribute attr=FuseAttributeFactory.buildAttribute(ElnprojectCELNE2244Item.基本属性组_启动日期, new Date());
		recordOpsBuilder.addUpdateAttr(attr);	
end
