package cho.carbon.fg.eln.rule.elnprojectcelne2244.impsecond

import cho.carbon.relation.RelationCorrelation;
import cho.carbon.fuse.improve.attribute.FuseAttributeFactory;
import cho.carbon.rrc.record.FGAttribute;
import cho.carbon.meta.enun.AttributeValueType;
import cho.carbon.relation.RecordRelation;
import cho.carbon.fuse.improve.attribute.FuseAttribute;
import cho.carbon.fuse.improve.attribute.OpsAttribute;
import cho.carbon.fuse.improve.attribute.mline.OpsMLineAttr;
import cho.carbon.message.MessageFactory;
import cho.carbon.fg.eln.common.CommonCalculation;
import cho.carbon.fg.eln.constant.BaseConstant;
import cho.carbon.fg.eln.constant.EnumKeyValue;
import cho.carbon.fg.eln.constant.RelationType;
import cho.carbon.fg.eln.constant.item.ElnprojectCELNE2244Item;
import cho.carbon.fg.eln.algorithm.eln.ElnprojectAlgorithm;

global java.lang.String recordCode;
global java.lang.String userCode;
global java.lang.String recordName;
global java.lang.String hostCode; 
global java.lang.String hostName;
global cho.carbon.rrc.record.FGRootRecord record;
global cho.carbon.complexus.FGRecordComplexus recordComplexus;
global cho.carbon.fuse.improve.ops.builder.FGRecordOpsBuilder recordOpsBuilder;
global java.util.List<FGRootRecord> relatedRecordList;
global java.util.List<Updatable> updateBeans;
global java.util.List<RemoveRecordInfo> removeRecordInfoList;
global java.util.List<RecordRelationOpsBuilder>  relatedRelationOpsBuilderList;
global cho.carbon.ops.builder.RecordRelationOpsBuilder relationOpsBuilder;
global java.util.List<Message> messageList;

/*
rule "实验项目组长必填"
	salience 60 
	when
		not RecordRelation(type == RelationType.RR_实验项目_组长_系统用户);
	then 
		messageList.add(MessageFactory.buildRefuseMessage("Failed", "实验项目", BaseConstant.TYPE_投料信息, "组长必填"));
end
*/

rule "实验项目项目组长为创建人"
	salience 60 
	when
		not RecordRelation(type == RelationType.RR_实验项目_组长_系统用户);
	then 
		relationOpsBuilder.putRelation(RelationType.RR_实验项目_创建人_系统用户, userCode);
	end

rule "实验项目的创建人"
	salience 30 
	when
		not RecordRelation(type == RelationType.RR_实验项目_创建人_系统用户);
	then  
		relationOpsBuilder.putRelation(RelationType.RR_实验项目_创建人_系统用户, userCode);
end

rule "实验项目组长也是组员"
	salience 30 
	when
		RecordRelation(type == RelationType.RR_实验项目_组长_系统用户, $rightCodeZh:rightCode);
		not RecordRelation(type == RelationType.RR_实验项目_组员_系统用户, $rightCodeZh != rightCode);
	then  
		relationOpsBuilder.putRelation(RelationType.RR_实验项目_组员_系统用户,  $rightCodeZh);
end

rule "生成项目报告"
	salience 20
	when
		FuseAttribute(name==ElnprojectCELNE2244Item.基本属性组_项目命令, getValue(AttributeValueType.INT) == EnumKeyValue.ENUM_实验项目命令_生成周报命令);
	then
		FGAttribute attr=FuseAttributeFactory.buildAttribute(ElnprojectCELNE2244Item.基本属性组_项目命令, null);
		recordOpsBuilder.addUpdateAttr(attr);	
		// 生成实验项目周报
		messageList.add(ElnprojectAlgorithm.createProjectReport(recordComplexus, recordCode, relationOpsBuilder, relatedRecordList));
end


