package cho.carbon.fg.eln.rule.consultprojectcelne4320.impthird

import cho.carbon.relation.RelationCorrelation;
import cho.carbon.fuse.improve.attribute.FuseAttributeFactory;
import cho.carbon.rrc.record.FGAttribute;
import cho.carbon.meta.enun.AttributeValueType;
import cho.carbon.relation.RecordRelation;
import cho.carbon.fuse.improve.attribute.FuseAttribute;
import cho.carbon.fuse.improve.attribute.OpsAttribute;
import cho.carbon.fuse.improve.attribute.mline.OpsMLineAttr;
import cho.carbon.message.MessageFactory;
import cho.carbon.fg.eln.common.CommonCalculation;
import cho.carbon.fg.eln.constant.BaseConstant;
import cho.carbon.fg.eln.constant.EnumKeyValue;
import cho.carbon.fg.eln.constant.RelationType;
import cho.carbon.fg.eln.constant.item.ConsultProjectCELNE4320Item;
import cho.carbon.fg.eln.algorithm.eln.ConsultProjectAlgorithm;

global java.lang.String recordCode;
global java.lang.String userCode;
global java.lang.String recordName;
global java.lang.String hostCode; 
global java.lang.String hostName;
global cho.carbon.rrc.record.FGRootRecord record;
global cho.carbon.complexus.FGRecordComplexus recordComplexus;
global cho.carbon.fuse.improve.ops.builder.FGRecordOpsBuilder recordOpsBuilder;
global java.util.List<FGRootRecord> relatedRecordList;
global java.util.List<Updatable> updateBeans;
global java.util.List<RemoveRecordInfo> removeRecordInfoList;
global java.util.List<RecordRelationOpsBuilder>  relatedRelationOpsBuilderList;
global cho.carbon.ops.builder.RecordRelationOpsBuilder relationOpsBuilder;
global java.util.List<Message> messageList;

rule "执行同意查阅命令"
	salience 20
	when
		FuseAttribute(name == ConsultProjectCELNE4320Item.基本属性组_命令, getValue(AttributeValueType.INT) == EnumKeyValue.ENUM_查阅项目命令_同意查阅);
	then  
		FGAttribute attr=FuseAttributeFactory.buildAttribute(ConsultProjectCELNE4320Item.基本属性组_命令, null);
		recordOpsBuilder.addUpdateAttr(attr);	
		// 执行同意查阅命令
		messageList.add(ConsultProjectAlgorithm.agreeConsult(recordComplexus, recordCode, relationOpsBuilder, relatedRecordList, recordOpsBuilder));
end