package cho.carbon.fg.eln.constant;
public class BaseConstant {
public static final String COLUMN_ABP0001 = "abp0001";
public static final String TYPE_系统用户="abcbe002";
public static final String TYPE_系统角色="abcbe003";
public static final String TYPE_系统权限="abcbe004";
public static final String TYPE_系统日志="abcbe095";
public static final String TYPE_仪器库存="celne2006";
public static final String TYPE_出库记录="celne2021";
public static final String TYPE_领用记录="celne2025";
public static final String TYPE_领用统计="celne2051";
public static final String TYPE_领用增量统计参数实体="celne2059";
public static final String TYPE_111="celne2065";
public static final String TYPE_实验记录="celne2189";
public static final String TYPE_实验项目="celne2244";
public static final String TYPE_组织机构="celne2249";
public static final String TYPE_物料基础信息="celne3393";
public static final String TYPE_实验检测结果="celne3421";
public static final String TYPE_实验操作过程="celne3433";
public static final String TYPE_实验安全分析="celne3447";
public static final String TYPE_投料信息="celne3466";
public static final String TYPE_项目报告="celne3499";
public static final String TYPE_项目参考文件="celne3533";
public static final String TYPE_物料库存信息="celne3551";
public static final String TYPE_物料出入库记录="celne3558";
public static final String TYPE_物料批次信息="celne3571";
public static final String TYPE_订单信息="celne3582";
public static final String TYPE_客户信息="celne3588";
public static final String TYPE_收发货地址信息="celne3597";
public static final String TYPE_附件资料="celne3610";
public static final String TYPE_订单物料目录="celne3629";
public static final String TYPE_项目执行计划="celne3705";
public static final String TYPE_项目日报="celne3729";
public static final String TYPE_物料预定="celne3756";
}
