package com.abc.rule.people.postimp

import cho.carbon.meta.enun.AttributeValueType;
import cho.carbon.fuse.improve.attribute.FuseAttributeFactory;
import cho.carbon.rrc.builder.FGRootRecordBuilder;
import cho.carbon.fuse.improve.attribute.OpsAttribute;
import cho.carbon.rrc.record.FGAttribute;
import cho.carbon.fuse.improve.attribute.FuseAttribute;
import cho.carbon.ops.builder.RecordRelationOpsBuilder;
import cho.carbon.rrc.record.FGRootRecord;
import cho.carbon.ops.builder.RecordRelationOpsBuilder;
import cho.carbon.sysdate.SystemDateTimeManager;
import cho.carbon.fuse.improve.attribute.leaf.FuseLeafAttribute;
import cho.carbon.util.CodeManager;

global java.lang.String hostCode; 
global java.lang.String hostType;

global java.lang.String userCode;
global java.lang.String recordCode;
global java.lang.String recordName;

global java.util.List recordRelationOpsBuilderNew;
global java.util.List rootRecordList;
global java.util.List attributeList;
global java.util.List addedLeafAttrList;
global java.util.Map removedLeafAttrMap;
global cho.carbon.rrc.record.FGRootRecord fgRootRecord;
global  cho.carbon.ops.builder.RecordRelationOpsBuilder recordRelationOpsBuilder;
global cho.carbon.complexus.FGRecordComplexus recordComplexus;

/*
//下面识别身份证号错误信息
rule "清空人口错误"
	salience 7
when
   $fa: FuseLeafAttribute(name==PeopleItem.人口错误信息_错误类型);
then  
	removedLeafAttrMap.put($fa.getLeafCode(), $fa.getName());
end 

rule "身份证校验错误"
	salience 6
when
    $idtype:FuseLeafAttribute(name==PeopleItem.证件信息_证件类型,getValue(AttributeValueType.INT)==EnumKeyValue.ENUM_证件类型_身份证,$leafCode:leafCode);
    $idValue:FuseLeafAttribute(name==PeopleItem.证件信息_证件号码,leafCode==$leafCode,CommonCalculation.isBasicLawful(getValue(AttributeValueType.STRING)));
    eval(!IDIntrospection.inspectId((String)$idValue.getValue(AttributeValueType.STRING)));
then 
	String code = CodeManager.newCode32();
	FuseLeafAttribute leafAttr = FuseAttributeFactory.buildFuseLeafAttribute($idValue.getCode(), PeopleItem.人口错误信息, code, PeopleItem.人口错误信息_错误类型, EnumKeyValue.ENUM_错误类型_身份证错误);
	addedLeafAttrList.add(leafAttr);
	FuseLeafAttribute leafAttr2 = FuseAttributeFactory.buildFuseLeafAttribute($idValue.getCode(), PeopleItem.人口错误信息, code, PeopleItem.人口错误信息_描述, "身份证校验错误");
	addedLeafAttrList.add(leafAttr2);
end

rule "身份证号出生日期与出生日期属性是否一致"
	salience 5
when 
    $idtype1:FuseLeafAttribute(name==PeopleItem.证件信息_证件类型, getValue(AttributeValueType.INT)==EnumKeyValue.ENUM_证件类型_身份证,$leafCode:leafCode);
    $idValue1:FuseLeafAttribute(name==PeopleItem.证件信息_证件号码,leafCode==$leafCode,CommonCalculation.isBasicLawful(getValue(AttributeValueType.STRING)));
   	$birthday: FuseAttribute(name==PeopleItem.出生日期 ,CommonCalculation.isBasicLawful(getValue(AttributeValueType.STRING)))
    eval(!IDIntrospection.inspectBirthday((String)$idValue1.getValue(AttributeValueType.STRING), (String)$birthday.getValue(AttributeValueType.STRING)));
then
	String code = CodeManager.newCode32();
	FuseLeafAttribute leafAttr = FuseAttributeFactory.buildFuseLeafAttribute($idValue1.getCode(), PeopleItem.人口错误信息, code, PeopleItem.人口错误信息_错误类型, EnumKeyValue.ENUM_错误类型_身份证错误);
	addedLeafAttrList.add(leafAttr);
	FuseLeafAttribute leafAttr2 = FuseAttributeFactory.buildFuseLeafAttribute($idValue1.getCode(), PeopleItem.人口错误信息, code, PeopleItem.人口错误信息_描述, "身份证号出生日期与出生日期属性不一致");
	addedLeafAttrList.add(leafAttr2);
end

rule "身份证号性别与性别属性是否一致"
	salience 5
when
    $idtype2:FuseLeafAttribute(name==PeopleItem.证件信息_证件类型,getValue(AttributeValueType.INT)==EnumKeyValue.ENUM_证件类型_身份证,$leafCode:leafCode);
    $idValue2:FuseLeafAttribute(name==PeopleItem.证件信息_证件号码,leafCode==$leafCode,CommonCalculation.isBasicLawful(getValue(AttributeValueType.STRING)));
   	$sex: FuseAttribute(name==PeopleItem.性别 ,CommonCalculation.isBasicLawful(getValue(AttributeValueType.STRING)))
    eval(!IDIntrospection.inspectSex((String)$idValue2.getValue(AttributeValueType.STRING), (String)$sex.getAttribute().getValue(AttributeValueType.STRING)));
then  
	String code = CodeManager.newCode32();
	FuseLeafAttribute leafAttr = FuseAttributeFactory.buildFuseLeafAttribute($idValue2.getCode(), PeopleItem.人口错误信息, code, PeopleItem.人口错误信息_错误类型, EnumKeyValue.ENUM_错误类型_身份证错误);
	addedLeafAttrList.add(leafAttr);
	FuseLeafAttribute leafAttr2 = FuseAttributeFactory.buildFuseLeafAttribute($idValue2.getCode(), PeopleItem.人口错误信息, code, PeopleItem.人口错误信息_描述, "身份证号性别与性别属性是不一致");
	addedLeafAttrList.add(leafAttr2);
end

*/